builders:
  widget_builder:
    import: "package:my_generator/builder.dart"
    builder_factories: ["widgetBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
